/**
 * Author:  1733565
 * Created: Nov 6, 2019
 */

DROP TABLE IF EXISTS TWEETS;

CREATE TABLE TWEEETS(
ID Int auto_increment,
USERNAME VARCHAR(50),
HANDLE VARCHAR(15),
DATEPOSTED VARCHAR(10),
TEXT VARCHAR(280),
IMAGEURL VARCHAR(250),
LARGEIMAGEURL VARCHAR(250),
RETWEETS INT,
LIKES INT,
FOLLOWERS INT,
FOLLOWING INT,
DESCRIPTION VARCHAR(250),
TWEETID VARCHAR(50),
PRIMARY KEY (ID));
